pip install asyncio
pip install black
pip install bs4
pip install chromedriver
pip install colored
pip install colorthief
pip install Pillow
pip install DateTime
pip install discord
pip install discord.py
pip install discum
pip install dnspython
pip install driver
pip install emoji
pip install gTTS
pip install image
pip install js
pip install lxml
pip install method
pip install moviepy
pip install mtranslate
pip install nekos.py
pip install node
pip install pipdeptree
pip install psutil
pip install pyarmor
pip install pyfiglet
pip install PyGetWindow
pip install pyinstaller
pip install pylint
pip install pymongo
pip install pyPrivnote
pip install python-obfuscator
pip install selector
pip install undetected-chromedriver
pip install wheel

pause
